# Generated by Django 4.1.1 on 2022-10-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-shirt', 'T'), ('Hoodie', 'H'), ('Outwear', 'O'), ('Skirt', 'S'), ('Pants', 'P'), ('D', 'Dress'), ('Long Sleeve', 'L'), ('Shorts', 'SH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M')], max_length=20),
        ),
    ]
