# Generated by Django 4.1.1 on 2022-10-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_item_category_alter_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-shirt', 'T'), ('Hoodie', 'H'), ('Outwear', 'O'), ('Skirt', 'S'), ('Pants', 'P'), ('Dress', 'D'), ('Long Sleeve', 'L'), ('Shorts', 'SH')], max_length=20),
        ),
    ]
