# Generated by Django 4.1.1 on 2022-10-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_favlist_created_at_remove_favlist_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='date',
        ),
    ]
